[project]
name = "osqp-eigen"
authors = ["Stefano Dafarra <stefano.dafarra@iit.it", "Giulio Romualdi <giulio.romualdi@iit.it>"]
# As this version is currently ignored, we do not
# waste effort in mantain it in synch with the value
# specified in CMakeLists.txt
version = "0.0.0"
description = "Simple Eigen-C++ wrapper for OSQP library."
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[target.win.activation.env]
CMAKE_INSTALL_PREFIX = "%CONDA_PREFIX%\\Library"

[target.unix.activation.env]
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"

[tasks]
configure = { cmd = [
    "cmake",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX",
    "-DBUILD_TESTING:BOOL=ON",
    # Use the cross-platform Ninja generator
    "-G",
    "Ninja",
    # The source is in the root directory
    "-S",
    ".",
    # We wanna build in the .build directory
    "-B",
    ".build",
]}

build = { cmd = "cmake --build .build --config Release", depends_on = ["configure"] }
test = { cmd = "ctest --test-dir .build --build-config Release", depends_on = ["build"] }
install = { cmd = ["cmake", "--install", ".build", "--config", "Release"], depends_on = ["build"] }
uninstall = { cmd = ["cmake", "--build", ".build", "--target", "uninstall"]}


[dependencies]
cmake = "*"
c-compiler = "*"
cxx-compiler = "*"
ninja = "*"
pkg-config = "*"
libosqp = "*"
eigen = "*"
ycm-cmake-modules = "*"
catch2 = "*"
